# ## 入力補完
# #-------- deoplete.vim
# [[plugins]]
# repo = 'Shougo/deoplete.nvim'
# hook_add = 'source ~/.config/nvim/plugins/deoplete.vim'
# on_i = 1

#-------- neosnippet.vim
[[plugins]]
repo = 'Shougo/neosnippet.vim'
hook_add = 'source ~/.config/nvim/plugins/neosnippet.vim'
on_i = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']

## filetype切り替え
#-------- vim-precious
[[plugins]] # カーソル位置のコンテキストに合わせてftを切り替える
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

#--------context_filetype
[[plugins]] # カーソル位置のコンテキストのftを判定するライブラリ
repo = 'Shougo/context_filetype.vim'

## HTML/CSS
#-------- emmet-vim
[[plugins]]
repo = 'mattn/emmet-vim'
hook_add = 'source ~/.config/nvim/plugins/emmet-vim.vim'
on_ft = ['html', 'css', 'js', 'eruby', 'javascript', 'riot']

#-------- html5.vim
[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']

#-------- vim-coloresque
[[plugins]]
repo = 'gko/vim-coloresque'
on_ft = ['html', 'css', 'js', 'eruby', 'vim']

## ruby
#-------- vim-ruby
[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['rb']

#-------- vim-rails
[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['rb']

# toml
#-------- vim-toml
[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

## javascript
#-------- vim-javascript
[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript']

#-------- yajs.vim
[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript']

#-------- es.next.syntax.vim
[[plugins]]
repo = 'othree/es.next.syntax.vim'
on_ft = ['javascript']

#-------- javascript-libraries-syntax.vim
[[plugins]]
repo = 'othree/javascript-libraries-syntax.vim'
on_ft = ['javascript', 'typescript']
hook_post_source = 'source ~/.config/nvim/plugins/javascript-libraries-syntax.vim'

#-------- vim-jsx-pretty
[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
on_ft = ['javascript']

#-------- typescript-vim
[[plugins]]
repo = 'leafgarland/typescript-vim'
on_fi = ['typescript']

#-------- vim-js-indent
[[plugins]]
repo = 'jason0x43/vim-js-indent'
on_fi = ['javascript', 'typescript', 'html']
hook_post_source = 'source ~/.config/nvim/plugins/vim-js-indent.vim'

#-------- typescript-tools
[[plugins]]
repo = 'clausreinke/typescript-tools'
on_ft = ['typescript']
hook_add = 'source ~/.config/nvim/plugins/typescript-tools.vim'

# #-------- vim-prettier
# [[plugins]]
# repo     = 'prettier/vim-prettier'
# build    = 'yarn install'
# on_ft    = ['javascript', 'typescript', 'vue', 'css', 'scss', 'json', 'markdown']
# hook_add = 'source ~/.config/nvim/plugins/vim-prettier.vim'

## json
#-------- vim-json
[[plugins]]
repo = 'elzr/vim-json'
hook_add = 'source ~/.config/nvim/plugins/vim-json.vim'
on_ft = ['json']
