# coc.nvim: hyper tool
[[plugins]]
repo = 'neoclide/coc.nvim'
build = './install.sh nightly'
hook_add = 'source ~/.config/nvim/plugins/coc-setting.vim'

# vimfiler depends unite.vim: explorer
[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/vimfiler'
hook_add = 'source ~/.config/nvim/plugins/vimfiler.vim'

# fzf: grep
[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = 0

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = 'source ~/.config/nvim/plugins/fzf.vim'

# colorscheme: color theme
[[plugins]]
repo = 'morhetz/gruvbox'
hook_add = 'colorscheme gruvbox'

# [[plugins]]
# repo = 'tomasr/molokai'
# hook_add = 'colorscheme molokai'

# [[plugins]]
# repo = 'mhartington/oceanic-next'
# hook_add = 'colorscheme OceanicNext'

# lightline.vim: status line
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'source ~/.config/nvim/plugins/lightline.vim'

# vim-anzu: search position
[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_add = 'source ~/.config/nvim/plugins/vim-anzu.vim'

# vim-trailing-whitespace: visualize white space
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
hook_add = 'source ~/.config/nvim/plugins/vim-trailing-whitespace.vim'

# vim-submode: easily chenge window size
[[plugins]]
repo = 'kana/vim-submode'
hook_add = 'source ~/.config/nvim/plugins/vim-submode.vim'

# auto-pairs: compleate brackets
[[plugins]]
repo = 'jiangmiao/auto-pairs'
hook_add = 'source ~/.config/nvim/plugins/auto-pairs.vim'

# vim-indent-guides: visualize indents
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = 'source ~/.config/nvim/plugins/vim-indent-guides.vim'

# tcomment_vim: comment out
[[plugins]]
repo = 'tomtom/tcomment_vim'
hook_add = 'source ~/.config/nvim/plugins/tcomment_vim.vim'

# switch.vim: switch boolean value
[[plugins]]
repo = 'AndrewRadev/switch.vim'
hook_add = 'source ~/.config/nvim/plugins/switch.vim'

# vim-gitgutter: visualize git diffrence
[[plugins]]
repo = 'airblade/vim-gitgutter'

# vim-operator-surround: vim-operator-surround depends vim-operator-user
[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'rhysd/vim-operator-surround'
hook_add = 'source ~/.config/nvim/plugins/vim-operator-surround.vim'

# quickrun.vim: run buffer code
[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = 'source ~/.config/nvim/plugins/quickrun.vim'

# vimshell: able to use shell on vim
[[plugins]]
repo = 'Shougo/vimshell.vim'
