## HTML/CSS
# emmet-vim: emmet
[[plugins]]
repo = 'mattn/emmet-vim'
hook_add = 'source ~/.config/nvim/plugins/emmet-vim.vim'
on_ft = ['html', 'css', 'eruby', 'javascript', 'javascript.jsx', 'typescript', 'typescript.tsx']

# html5.vim: syntax html
[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']

# vim-coloresque: change background color on color code
[[plugins]]
repo = 'gko/vim-coloresque'
on_ft = ['html', 'css', 'eruby', 'vim', 'javascript', 'javascript.jsx', 'typescript', 'typescript.tsx']

## ruby
# vim-ruby: syntax ruby
[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby']

## toml
# vim-toml: syntax toml
[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

## javascript, typescript
# typescript-vim: syntax typescript
[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['javascript','javascript.jsx', 'typescript', 'typescript.tsx']
hook_add = 'source ~/.config/nvim/plugins/typescript-vim.vim'

# vim-jsx-pretty
[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
on_ft = ['javascript', 'javascript.jsx', 'typescript', 'typescript.tsx']

# yajs.vim
[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript', 'javascript.jsx', 'typescript', 'typescript.tsx']

## json
# vim-json: syntax json
[[plugins]]
repo = 'elzr/vim-json'
hook_add = 'source ~/.config/nvim/plugins/vim-json.vim'
on_ft = ['json']

## rust
# rust.vim: syntax rust
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rs']

## markdown preview
[[plugins]]
repo = 'plasticboy/vim-markdown'
hook_add = 'source ~/.config/nvim/plugins/vim-markdown.vim'
on_ft = ['markdown']

[[plugins]]
repo = 'kannokanno/previm'
hook_add = 'source ~/.config/nvim/plugins/previm.vim'
on_ft = ['markdown']

[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = ['markdown']

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
on_ft = ['markdown']
hook_add = 'source ~/.config/nvim/plugins/vim-table-mode.vim'
